#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION="0.0.7"

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/ManPageEditor
find ManPageEditor -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/ManPageEditor/makepkg

mv /tmp/ManPageEditor /tmp/ManPageEditor-${VERSION}
cd /tmp/ManPageEditor-${VERSION}

./remakesourcelist
aclocal
autoheader
touch NEWS README AUTHORS
automake --add-missing --copy
autoconf
rm -rf ./autom4te.cache
rm ./compile ./missing ./COPYING ./AUTHORS ./NEWS ./README

cd ..

tar -czvf ManPageEditor-${VERSION}.tar.gz ManPageEditor-${VERSION}
rm -r /tmp/ManPageEditor-${VERSION}