.TH "manpageeditor" "1" "0.0.10" "K.D.Hedger" ""
.SH "NAME"
Manpage Editor - Create man pages.
.br
.SH "SYNTAX"
manpageeditor \fBFILE\fR
.br

.SH "DESCRIPTION"
A nice GUI for editing manpages, different sections are shown in different tabs.
.br
Can also import and preview manpages.
.br
.SH "FILES"
$HOME/editor.rc
.br
$HOME/editor.window.rc
.br
.SH "AUTHORS"
Bugs, suggestions etc to:
.br
kdhedger68713@gmail.com
.br
.SH "SEE ALSO"
\fBXfce Theme Manager:\fR
.br
	\fIhttp://xfce-look.org/content/show.php/Xfce-Theme-Manager?content=149647\fR
.br

\fBXfce4 Composite Editor:\fR
.br
	\fIhttp://gtk-apps.org/content/show.php/?content=149523\fR
.br

\fBKKEdit:\fR
.br
	\fIhttp://gtk-apps.org/content/show.php/KKEdit?content=158161\fR
.br

\fBGtkSu:\fR
.br
	\fIhttp://gtk-apps.org/content/show.php/GtkSu?content=158974\fR
.br

