.TH "manpageeditor" "1" "0.1.5" "K.D.Hedger" ""
.SH "NAME"
Manpage Editor - Create man pages.
.br

.SH "SYNOPSIS"
manpageeditor [ \fBOPTIONS \fR] [ \fIFILE\fR ]
.br

.SH "DESCRIPTION"
A nice GUI for editing manpages, different sections are shown in different tabs.
.br
Can also import and preview manpages.
.br

.SH "OPTIONS"
\fB-i, --import \fR\fINAME\fR
.br
     Import system manpage \fINAME\fR
.br

\fB-s, --section \fR\fISECTION\fR
.br
     Specify section \fISECTION\fR
.br

\fB-v, --version\fR
.br
     Print version info and exit
.br

\fB-?, --help\fR
.br
     Print quick help.
.br

.SH "FILES"
$HOME/editor.rc
.br
$HOME/editor.window.rc
.br

.SH "AUTHORS"
Bugs, suggestions etc to:
.br
keithdhedger@gmail.com
.br

.SH "SEE ALSO"
\fBWebsite\fR:
.br
https://keithdhedger.github.io/
.br

\fBKKEdit\fR:
.br
https://keithdhedger.github.io/KKEdit/
.br

\fBKKTerminal\fR
.br
https://keithdhedger.github.io/pages/kkterminal/kkterminal.html
.br

\fBXDecorations\fR:
.br
https://keithdhedger.github.io/pages/xdecorations/xdecorations.html
.br

\fBXfce-Theme-Manager\fR:
.br
https://keithdhedger.github.io/pages/apps.html#themeed
.br

\fBXfce4-Composite-Editor\fR:
.br
https://keithdhedger.github.io/pages/apps.html#xfcecomp
.br

\fBManpage Editor\fR:
.br
https://keithdhedger.github.io/pages/manpageeditor/manpageeditor.html
.br

\fBGtkSu\fR:
.br
https://keithdhedger.github.io/pages/gtksu/gtksu.html
.br

\fBASpell GUI\fR:
.br
https://keithdhedger.github.io/pages/aspellgui/aspelgui.html
.br

\fBClipboard Viewer\fR:
.br
https://keithdhedger.github.io/pages/clipviewer/clip.html
.br

