.TH "manpageeditor" "1" "0.1.2" "K.D.Hedger" ""
.SH "NAME"
Manpage Editor - Create man pages.
.br

.SH "SYNTAX"
manpageeditor \fIFILE\fR
.br

.SH "DESCRIPTION"
A nice GUI for editing manpages, different sections are shown in different tabs.
.br
Can also import and preview manpages.
.br

.SH "FILES"
$HOME/editor.rc
.br
$HOME/editor.window.rc
.br

.SH "AUTHORS"
Bugs, suggestions etc to:
.br
kdhedger68713@gmail.com
.br

.SH "SEE ALSO"
\fBWebsite\fR:
.br
http://khapplications.darktech.org/index.html
.br

\fBKKEdit\fR:
.br
http://kkedit.darktech.org/
.br

\fBKKTerminal\fR
.br
http://khapplications.darktech.org/pages/kkterminal/kkterminal.html
.br

\fBXDecorations\fR:
.br
http://khapplications.darktech.org/pages/xdecorations/xdecorations.html
.br

\fBXfce-Theme-Manager\fR:
.br
http://khapplications.darktech.org/pages/apps.html#themeed
.br

\fBXfce4-Composite-Editor\fR:
.br
http://khapplications.darktech.org/pages/apps.html#xfcecomp
.br

\fBManpage Editor\fR:
.br
http://khapplications.darktech.org/pages/manpageeditor/help.html
.br

\fBGtkSu\fR:
.br
http://khapplications.darktech.org/pages/gtksu/gtksu.html
.br

\fBASpell GUI\fR:
.br
http://khapplications.darktech.org/pages/aspellgui/aspelgui.html
.br

\fBClipboard Viewer\fR:
.br
http://khapplications.darktech.org/pages/clipviewer/clip.html
.br

Development versions can be found here:
.br
http://github.com/KeithDHedger
.br

